<?php
/**
 * Media Engine Scanner Service
 *
 * @package WP_Genius
 * @subpackage Modules/MediaEngine
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class W2P_Media_Scanner_Service {

	public function get_pending_attachments( $limit = 100, $offset = 0 ) {
		global $wpdb;
		$mime_types = $this->get_supported_mime_types();
		if ( empty( $mime_types ) ) {
			return array();
		}
		$mime_placeholders = implode( ',', array_fill( 0, count( $mime_types ), '%s' ) );
		// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders -- IN placeholders are composed of %s (generated by array_fill); parameters are bound via prepare.
		$query = $wpdb->prepare(
			"SELECT p.ID FROM {$wpdb->posts} p
			LEFT JOIN {$wpdb->postmeta} pm ON (p.ID = pm.post_id AND pm.meta_key = 'advmo_offloaded' AND pm.meta_value = '1')
			LEFT JOIN {$wpdb->postmeta} pmf ON (p.ID = pmf.post_id AND pmf.meta_key = '_w2p_media_failed')
			LEFT JOIN {$wpdb->postmeta} pmp ON (p.ID = pmp.post_id AND pmp.meta_key = '_w2p_rewrite_pending')
			WHERE p.post_type = 'attachment' AND p.post_mime_type IN ($mime_placeholders)
				AND ( pm.post_id IS NULL OR pmp.post_id IS NOT NULL ) AND pmf.post_id IS NULL
			ORDER BY p.ID DESC LIMIT %d OFFSET %d",
			array_merge( $mime_types, array( $limit, $offset ) )
		);
		// phpcs:enable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared -- $query is the return value of the $wpdb->prepare() above (LIMIT/OFFSET bound via %d).
		return array_map( 'intval', $wpdb->get_col( $query ) );
	}

	public function get_pending_count() {
		global $wpdb;
		$mime_types = $this->get_supported_mime_types();
		if ( empty( $mime_types ) ) {
			return 0;
		}
		$mime_placeholders = implode( ',', array_fill( 0, count( $mime_types ), '%s' ) );
		// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders
		$query = $wpdb->prepare(
			"SELECT COUNT(*) FROM {$wpdb->posts} p
			LEFT JOIN {$wpdb->postmeta} pm ON (p.ID = pm.post_id AND pm.meta_key = 'advmo_offloaded' AND pm.meta_value = '1')
			LEFT JOIN {$wpdb->postmeta} pmf ON (p.ID = pmf.post_id AND pmf.meta_key = '_w2p_media_failed')
			LEFT JOIN {$wpdb->postmeta} pmp ON (p.ID = pmp.post_id AND pmp.meta_key = '_w2p_rewrite_pending')
			WHERE p.post_type = 'attachment' AND p.post_mime_type IN ($mime_placeholders)
				AND ( pm.post_id IS NULL OR pmp.post_id IS NOT NULL ) AND pmf.post_id IS NULL",
			$mime_types
		);
		// phpcs:enable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
		return (int) $wpdb->get_var( $query );
	}

	private function get_supported_mime_types() {
		return array( 'image/jpeg', 'image/png', 'image/gif', 'image/webp' );
	}
}

// Backward compatibility alias.
if ( ! class_exists( 'MediaEngineScannerService', false ) ) {
	class_alias( 'W2P_Media_Scanner_Service', 'MediaEngineScannerService' );
}
