<?php
/**
 * Media Engine Scanner Service
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class MediaEngineScannerService {
	private $settings;

	public function __construct() {
		$this->settings = W2P_Settings::tab_with_legacy( 'media_engine_tabs', 'w2p_media_turbo_settings', array() );
	}

	public function get_pending_attachments( $limit = 100, $offset = 0 ) {
		global $wpdb;
		$mime_types = $this->get_supported_mime_types();
		if ( empty( $mime_types ) ) {
			return array();
		}
		$mime_types[]      = 'image/webp';
		$mime_types        = array_unique( $mime_types );
		$mime_placeholders = implode( ',', array_fill( 0, count( $mime_types ), '%s' ) );
		// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders -- IN placeholders are composed of %s (generated by array_fill); parameters are bound via prepare.
		$query = $wpdb->prepare(
			"SELECT p.ID FROM {$wpdb->posts} p
			LEFT JOIN {$wpdb->postmeta} pm ON (p.ID = pm.post_id AND pm.meta_key = 'advmo_offloaded' AND pm.meta_value = '1')
			LEFT JOIN {$wpdb->postmeta} pmf ON (p.ID = pmf.post_id AND pmf.meta_key = '_w2p_media_failed')
			LEFT JOIN {$wpdb->postmeta} pmp ON (p.ID = pmp.post_id AND pmp.meta_key = '_w2p_rewrite_pending')
			WHERE p.post_type = 'attachment' AND p.post_mime_type IN ($mime_placeholders)
				AND ( pm.post_id IS NULL OR pmp.post_id IS NOT NULL ) AND pmf.post_id IS NULL
			ORDER BY p.ID DESC LIMIT %d OFFSET %d",
			array_merge( $mime_types, array( $limit, $offset ) )
		);
		// phpcs:enable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared -- $query is the return value of the $wpdb->prepare() above (LIMIT/OFFSET bound via %d).
		return array_map( 'intval', $wpdb->get_col( $query ) );
	}

	public function get_pending_count() {
		return count( $this->get_pending_attachments( 1000, 0 ) );
	}

	private function get_supported_mime_types() {
		// Hardcoded support for all target types
		return array( 'image/jpeg', 'image/png', 'image/gif' );
	}
}
